icon: 'http://127.0.0.1:8000/storage/media/H6OyfuxHjnP4Ncsryl7eBm2V4YxIjOdCEfZhaEfF.svg'
columns:
    - image
    - project
    - link
    - status
meta:
    
    project:
        control: text
        default: 'Awesome Project'
        validate: string|required|max:255

    head:
        fields:
            client:
                control: text
                validate: string|max:255
            date:
                control: date
                validate: date|max:255
            role:
                control: select
                values:
                    Full-stack Dev: full
                    Frontend Dev: frontend
                    Backend Dev: backend
                validate: required
            type:
                control: text
                validate: string|required|max:255
    challenge:
        control: richtext
        validate: string
    
    solution:
        control: richtext
        validate: string

    general_group:
        fields:
            image:
                control: image
                validate: string
            gallery:
                control: images
                default: []
                validate: array

    description:
        control: textarea
        validate: string
        
    technical_group:
        fields:
            link:
                control: text
                validate: url
            framework:
                control: text
                validate: string
            status:
                control: select
                default: On-going
                values:
                    On-going: On-going
                    Done: Done
                validate: string|required
            sticky:
                control: checkbox
                default:
                    - Sticky
                values:
                    Sticky: Sticky
                validate: array