<script setup>
import AppHead from '@/Components/CustomComponents/AppHead.vue';
import InputError from '@/Components/InputError.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import GuestLayout from '@/Layouts/GuestLayout.vue';
import { useForm } from '@inertiajs/vue3';
import { ref } from 'vue';

const pin = ref([
    null, null, null, null, null, null
]);

const form = useForm({
    'one_time_password': null
});

const handleSubmit = () => {
    form.one_time_password = pin.value.join('');
    form.post( route( '2fa.verify' ), {
        onFinish: () => {
            pin.value = [null, null, null, null, null, null];
        }
    } );
};

const pinInputs = ref([]);
const moveCursor = (index) => {
    if( pin.value[index] !== null && pin.value[index] !== '' ) {
        // Move to the next input if it's within bounds
        const nextInput = pinInputs.value[index + 1];
        if( nextInput ) {
            nextInput.focus();
        } else {
            pinInputs.value[0].focus();
            handleSubmit();
        }
    }
};
</script>

<template>
    <GuestLayout>
        <AppHead title="2fa" />

        <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100 text-center mb-2">Sign in using authenticator</h1>

        <p class="mb-4 text-sm text-gray-600 dark:text-gray-400 text-center">To continue, please enter 6-digit verification code generated by <b>your authenticator app</b>.</p>

        <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <form @submit.prevent="handleSubmit">
            <div class="flex flex-row flex-nowrap items-center">
                <template v-for="(n, index) in 6">
                    <span v-if="index === 3 " class="p-1">-</span>
                    <input type="number" maxlength="1" autofocus ref="pinInputs" :ref="el => pinInputs.value[index] = el" v-model="pin[index]" @input="moveCursor(index)" class="grow shrink w-10 m-1 border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm input-2fa text-center" />
                </template>
            </div>
            <InputError class="mt-2" :message="form.errors.one_time_password" />
            <center>
                <PrimaryButton class="h-10 mt-4">Continue</PrimaryButton>
            </center>
        </form>
    </GuestLayout>
</template>

<style scoped>
.input-2fa::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}
.input-2fa {
    -moz-appearance: textfield;
}
</style>