<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import AppHead from '@/Components/CustomComponents/AppHead.vue';
import InputError from '@/Components/InputError.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import TitleBar from '@/Components/CustomComponents/TitleBar.vue';
import { ref } from 'vue';
import { useForm } from '@inertiajs/vue3';

defineProps([ 'status', 'qrCode', 'secret' ]);

const pin = ref([
    null, null, null, null, null, null
]);

const form = useForm({
    'one_time_password': null
});

const handleSubmit = () => {
    form.one_time_password = pin.value.join('');
    form.post( route( '2fa.enable' ), {
        onFinish: () => {
            pin.value = [null, null, null, null, null, null];
        }
    } );
};

const pinInputs = ref([]);
const moveCursor = (index) => {
    if( pin.value[index] !== null && pin.value[index] !== '' ) {
        // Move to the next input if it's within bounds
        const nextInput = pinInputs.value[index + 1];
        if( nextInput ) {
            nextInput.focus();
        } else {
            pinInputs.value[0].focus();
            handleSubmit();
        }
    }
};
</script>

<template>
    <AppHead title="Enable 2FA" />

    <AuthenticatedLayout>
        <template #header>
            <TitleBar title="Enable Two-Factor Authentication" :back="true" />
        </template>

        <div class="py-2">
            <div class="sm:px-6 lg:px-8 space-y-6">
                
                <div class="mx-auto max-w-96 w-full text-center">
                    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
                        Scan the QR code below using your authenticator app.
                    </p>

                    <div v-html="qrCode" class="flex flex-col my-5 items-center"></div>

                    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
                        After scanning the QR code, enter the 6-digit code generated by your authenticator app.
                    </p>

                    <form @submit.prevent="handleSubmit">
                        <div class="flex flex-row flex-nowrap items-center">
                            <template v-for="(n, index) in 6">
                                <span v-if="index === 3 " class="p-1">-</span>
                                <input type="number" maxlength="1" autofocus ref="pinInputs" :ref="el => pinInputs.value[index] = el" v-model="pin[index]" @input="moveCursor(index)" class="grow shrink w-10 m-1 border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm input-2fa text-center" />
                            </template>
                        </div>
                        <InputError class="mt-2" :message="form.errors.one_time_password" />
                        <center>
                            <PrimaryButton class="h-10 mt-4">Confirm and Enable 2FA</PrimaryButton>
                        </center>
                    </form>
                </div>

            </div>
        </div>
    </AuthenticatedLayout>
</template>

<style scoped>
.input-2fa::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}
.input-2fa {
    -moz-appearance: textfield;
}
</style>